public enum CardType
{
    basicHp = 0,
    basicEnergy,
    basicWeapon,
    basicAbsorb,
    basicClearBullets,
    basicBlock,
    intermediateHp,
    intermediateEnergy,
    intermediateWeapon,
    intermediateAbsorb,
    intermediateBlock,
    advancedHp,
    advancedEnergy,
    advancedWeapon,
    advancedAbsorb,
    advancedBlock,
    basicRefreshHand,
    basicScoreMultiplier,
    intermediateScoreMultiplier,
    advancedScoreMultiplier,
}